[package]
name = "hades"
version = "0.1.0"
authors = ["traxys <quentin@familleboyer.net>"]
edition = "2021"

[dependencies]
apis = { path = "../apis" }
ogma = { path = "../ogma" }

[dev-dependencies]
macro_rules_attribute = "0.2.0"
